""

# buildifier: disable=module-docstring
module(
    name = "bazel_arm_examples",
    version = "0.1",
)

bazel_dep(name = "rules_cc", version = "0.1.1")
bazel_dep(name = "platforms", version = "0.0.11")

git_override(module_name="bazel_utilities", remote="https://github.com/0-Sacha/bazel_utilities.git", commit="230196b5427877a13e38a6e9d3b5a3b336ff2480")
# local_path_override(module_name = "bazel_utilities", path = "../../../bazel_utilities/")

# Replace with git_override from my repo `https://github.com/0-Sacha/bazel_arm.git`
local_path_override(module_name = "bazel_arm", path = "../../")

bazel_dep(name = "bazel_utilities", version = "0.0.1", dev_dependency = True)
bazel_dep(name = "bazel_arm", version = "0.0.1", dev_dependency = True)

arm_gcc_toolchain_extension = use_extension("@bazel_arm//arm_gcc:rules.bzl", "arm_gcc_toolchain_extension", dev_dependency = True)
inject_repo(arm_gcc_toolchain_extension, "platforms", "bazel_utilities")
arm_gcc_toolchain_extension.arm_gcc_toolchain(
    name = "my_arm-none-eabi",
    toolchain_type = "arm-none-eabi",
    specs = [ "nosys" ],
)
arm_gcc_toolchain_extension.arm_gcc_toolchain(
    name = "my_aarch64-none-elf",
    toolchain_type = "aarch64-none-elf",
    specs = [ "nosys" ],
)
use_repo(arm_gcc_toolchain_extension, "my_arm-none-eabi")
use_repo(arm_gcc_toolchain_extension, "my_aarch64-none-elf")
# register_toolchains("@my_arm-none-eabi//:toolchain")
# register_toolchains("@my_aarch64-none-elf//:toolchain")

arm_llvm_toolchain_extension = use_extension("@bazel_arm//arm_llvm:rules.bzl", "arm_llvm_toolchain_extension", dev_dependency = True)
inject_repo(arm_llvm_toolchain_extension, "platforms", "bazel_utilities")
arm_llvm_toolchain_extension.arm_llvm_toolchain(
    name = "my_arm_llvm_picolibc",
    toolchain_type = "arm-none-eabi",
    toolchain_multilib = "armv7m_soft_fpv4_sp_d16_exn_rtti",
    toolchain_overlay = "picolibc",
    target = "arm-none-eabi",
    mcuopts = [ "-mfloat-abi=soft" ],
)
arm_llvm_toolchain_extension.arm_llvm_toolchain(
    name = "my_arm_llvm_newlib",
    toolchain_type = "arm-none-eabi",
    toolchain_multilib = "armv7m_soft_fpv4_sp_d16_exn_rtti",
    toolchain_overlay = "newlib",
    target = "arm-none-eabi",
    mcuopts = [ "-mfloat-abi=soft" ],
    specs = [ "nosys" ],
)
use_repo(arm_llvm_toolchain_extension, "my_arm_llvm_picolibc")
use_repo(arm_llvm_toolchain_extension, "my_arm_llvm_newlib")
# register_toolchains("@my_arm_llvm_picolibc//:toolchain")
# register_toolchains("@my_arm_llvm_newlib//:toolchain")
