""

# buildifier: disable=module-docstring
module(
    name = "bazel_arm_examples",
    version = "0.1",
)

bazel_dep(name = "rules_cc", version = "0.0.10")
bazel_dep(name = "platforms", version = "0.0.10")

git_override(module_name="bazel_utilities", remote="https://github.com/0-Sacha/bazel_utilities.git", commit="1c3c6c01dcccc6c922c4955c92aa7c3c015a9d1c")
# local_path_override(module_name = "bazel_utilities", path = "../../../bazel_utilities/")

# Replace with git_override from my repo `https://github.com/0-Sacha/bazel_arm.git`
local_path_override(module_name = "bazel_arm", path = "../../")

bazel_dep(name = "bazel_utilities", version = "0.0.1", dev_dependency = True)
bazel_dep(name = "bazel_arm", version = "0.0.1", dev_dependency = True)

arm_toolchain_extension = use_extension("@bazel_arm//arm_gcc:rules.bzl", "arm_toolchain_extension", dev_dependency = True)
inject_repo(arm_toolchain_extension, "platforms", "bazel_utilities")
arm_toolchain_extension.arm_toolchain(
    name = "my_arm-none-eabi",
    toolchain_type = "arm-none-eabi",
    specs = [ "nosys" ],
)
arm_toolchain_extension.arm_toolchain(
    name = "my_aarch64-none-elf",
    toolchain_type = "aarch64-none-elf",
    specs = [ "nosys" ],
)
use_repo(arm_toolchain_extension, "my_arm-none-eabi")
use_repo(arm_toolchain_extension, "my_aarch64-none-elf")
# register_toolchains("@my_arm-none-eabi//:toolchain")
# register_toolchains("@my_aarch64-none-elf//:toolchain")
