name: gcc/aarch64-none-elf

on:
  push:
    branches:
      - '**'
  # pull_request:
  #   branches:
  #     - '**'

jobs:
  windows-latest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bazelbuild/setup-bazelisk@v3
    - name: Mount bazel cache
      uses: actions/cache@v4
      with:
        path: "~/.cache/bazel"
        key: bazel
    - name: Build HelloWorld
      run: bazelisk build --config=aarch64-none-elf //HelloWorld:HelloWorld
      working-directory: examples/common

  ubuntu-latest-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bazelbuild/setup-bazelisk@v3
    - name: Mount bazel cache
      uses: actions/cache@v4
      with:
        path: "~/.cache/bazel"
        key: bazel
    - name: Build HelloWorld
      run: bazelisk build --config=aarch64-none-elf //HelloWorld:HelloWorld
      working-directory: examples/common

  ubuntu-latest-aarch64:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
    - uses: bazelbuild/setup-bazelisk@v3
    - name: Mount bazel cache
      uses: actions/cache@v4
      with:
        path: "~/.cache/bazel"
        key: bazel
    - name: Build HelloWorld
      run: bazelisk build --config=aarch64-none-elf //HelloWorld:HelloWorld
      working-directory: examples/common
